// PG specyfic OLE DB properties

//PG_SERVER_PORT - postmaster TCP IP port number

#define DBPROP_PG_SERVER_PORT 0xf000
#define PG_SERVER_PORT_Type VT_I4
#define PG_SERVER_PORT_Value 5432
#define PG_SERVER_PORT_Flags (DBPROPFLAGS_DBINIT | DBPROPFLAGS_READ|DBPROPFLAGS_WRITE)

#define DBPROP_PG_DATABASE 0xf001
#define PG_DATABASE_Type VT_BSTR
#define PG_DATABASE_Value L""
#define PG_DATABASE_Flags (DBPROPFLAGS_DBINIT | DBPROPFLAGS_READ|DBPROPFLAGS_WRITE)